# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /exthome/dsm5/rascals/gitOCCA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /exthome/dsm5/rascals/gitOCCA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /exthome/dsm5/rascals/gitOCCA/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /exthome/dsm5/rascals/gitOCCA/CMakeFiles /exthome/dsm5/rascals/gitOCCA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /exthome/dsm5/rascals/gitOCCA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named occa

# Build rule for target.
occa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 occa
.PHONY : occa

# fast build rule for target.
occa/fast:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/build
.PHONY : occa/fast

#=============================================================================
# Target rules for targets named occac_header_gen

# Build rule for target.
occac_header_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 occac_header_gen
.PHONY : occac_header_gen

# fast build rule for target.
occac_header_gen/fast:
	$(MAKE) -f CMakeFiles/occac_header_gen.dir/build.make CMakeFiles/occac_header_gen.dir/build
.PHONY : occac_header_gen/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f CMakeFiles/version.dir/build.make CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f examples/simple/CMakeFiles/simple.dir/build.make examples/simple/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named simple_c

# Build rule for target.
simple_c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_c
.PHONY : simple_c

# fast build rule for target.
simple_c/fast:
	$(MAKE) -f examples/simple/CMakeFiles/simple_c.dir/build.make examples/simple/CMakeFiles/simple_c.dir/build
.PHONY : simple_c/fast

#=============================================================================
# Target rules for targets named simple_f90

# Build rule for target.
simple_f90: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_f90
.PHONY : simple_f90

# fast build rule for target.
simple_f90/fast:
	$(MAKE) -f examples/simple/CMakeFiles/simple_f90.dir/build.make examples/simple/CMakeFiles/simple_f90.dir/build
.PHONY : simple_f90/fast

#=============================================================================
# Target rules for targets named fd2d

# Build rule for target.
fd2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fd2d
.PHONY : fd2d

# fast build rule for target.
fd2d/fast:
	$(MAKE) -f examples/fd2d/CMakeFiles/fd2d.dir/build.make examples/fd2d/CMakeFiles/fd2d.dir/build
.PHONY : fd2d/fast

libocca/occa.o: libocca/occa.cpp.o
.PHONY : libocca/occa.o

# target to build an object file
libocca/occa.cpp.o:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/libocca/occa.cpp.o
.PHONY : libocca/occa.cpp.o

libocca/occa.i: libocca/occa.cpp.i
.PHONY : libocca/occa.i

# target to preprocess a source file
libocca/occa.cpp.i:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/libocca/occa.cpp.i
.PHONY : libocca/occa.cpp.i

libocca/occa.s: libocca/occa.cpp.s
.PHONY : libocca/occa.s

# target to generate assembly for a file
libocca/occa.cpp.s:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/libocca/occa.cpp.s
.PHONY : libocca/occa.cpp.s

liboccac/occac.o: liboccac/occac.cpp.o
.PHONY : liboccac/occac.o

# target to build an object file
liboccac/occac.cpp.o:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccac/occac.cpp.o
.PHONY : liboccac/occac.cpp.o

liboccac/occac.i: liboccac/occac.cpp.i
.PHONY : liboccac/occac.i

# target to preprocess a source file
liboccac/occac.cpp.i:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccac/occac.cpp.i
.PHONY : liboccac/occac.cpp.i

liboccac/occac.s: liboccac/occac.cpp.s
.PHONY : liboccac/occac.s

# target to generate assembly for a file
liboccac/occac.cpp.s:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccac/occac.cpp.s
.PHONY : liboccac/occac.cpp.s

liboccac/occac_header_gen.o: liboccac/occac_header_gen.c.o
.PHONY : liboccac/occac_header_gen.o

# target to build an object file
liboccac/occac_header_gen.c.o:
	$(MAKE) -f CMakeFiles/occac_header_gen.dir/build.make CMakeFiles/occac_header_gen.dir/liboccac/occac_header_gen.c.o
.PHONY : liboccac/occac_header_gen.c.o

liboccac/occac_header_gen.i: liboccac/occac_header_gen.c.i
.PHONY : liboccac/occac_header_gen.i

# target to preprocess a source file
liboccac/occac_header_gen.c.i:
	$(MAKE) -f CMakeFiles/occac_header_gen.dir/build.make CMakeFiles/occac_header_gen.dir/liboccac/occac_header_gen.c.i
.PHONY : liboccac/occac_header_gen.c.i

liboccac/occac_header_gen.s: liboccac/occac_header_gen.c.s
.PHONY : liboccac/occac_header_gen.s

# target to generate assembly for a file
liboccac/occac_header_gen.c.s:
	$(MAKE) -f CMakeFiles/occac_header_gen.dir/build.make CMakeFiles/occac_header_gen.dir/liboccac/occac_header_gen.c.s
.PHONY : liboccac/occac_header_gen.c.s

liboccaf/occaf.o: liboccaf/occaf.c.o
.PHONY : liboccaf/occaf.o

# target to build an object file
liboccaf/occaf.c.o:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccaf/occaf.c.o
.PHONY : liboccaf/occaf.c.o

liboccaf/occaf.i: liboccaf/occaf.c.i
.PHONY : liboccaf/occaf.i

# target to preprocess a source file
liboccaf/occaf.c.i:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccaf/occaf.c.i
.PHONY : liboccaf/occaf.c.i

liboccaf/occaf.s: liboccaf/occaf.c.s
.PHONY : liboccaf/occaf.s

# target to generate assembly for a file
liboccaf/occaf.c.s:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccaf/occaf.c.s
.PHONY : liboccaf/occaf.c.s

liboccaf/occaf.o: liboccaf/occaf.f90.o
.PHONY : liboccaf/occaf.o

# target to build an object file
liboccaf/occaf.f90.o:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccaf/occaf.f90.o
.PHONY : liboccaf/occaf.f90.o

liboccaf/occafFunctions.o: liboccaf/occafFunctions.f90.o
.PHONY : liboccaf/occafFunctions.o

# target to build an object file
liboccaf/occafFunctions.f90.o:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccaf/occafFunctions.f90.o
.PHONY : liboccaf/occafFunctions.f90.o

liboccaf/occafTypes.o: liboccaf/occafTypes.f90.o
.PHONY : liboccaf/occafTypes.o

# target to build an object file
liboccaf/occafTypes.f90.o:
	$(MAKE) -f CMakeFiles/occa.dir/build.make CMakeFiles/occa.dir/liboccaf/occafTypes.f90.o
.PHONY : liboccaf/occafTypes.f90.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dist"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... occa"
	@echo "... occac_header_gen"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... version"
	@echo "... simple"
	@echo "... simple_c"
	@echo "... simple_f90"
	@echo "... fd2d"
	@echo "... libocca/occa.o"
	@echo "... libocca/occa.i"
	@echo "... libocca/occa.s"
	@echo "... liboccac/occac.o"
	@echo "... liboccac/occac.i"
	@echo "... liboccac/occac.s"
	@echo "... liboccac/occac_header_gen.o"
	@echo "... liboccac/occac_header_gen.i"
	@echo "... liboccac/occac_header_gen.s"
	@echo "... liboccaf/occaf.o"
	@echo "... liboccaf/occaf.i"
	@echo "... liboccaf/occaf.s"
	@echo "... liboccaf/occaf.o"
	@echo "... liboccaf/occafFunctions.o"
	@echo "... liboccaf/occafTypes.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

